"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from pastk import __version__
from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {"packages":['pynput', 'pastk'], "iconfile":"resources/logo/PasTk_logo.icns"}

setup(
    app=APP,
    name="PasTk",
    version=__version__,
    author="Lambol.Michael.Alee",
    author_email="lambolalee@protonmail.ch",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
